CREATE TABLE employment_logs(
    employment_log_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY, 
    first_name VARCHAR(50) NOT NULL, 
    last_name VARCHAR(50) NOT NULL, 
    employment_action CHAR(5) NOT NULL, 
    employment_status_updtd_tmstmp TIMESTAMP NOT NULL,
    CONSTRAINT emp_act_check CHECK (
        employment_action = 'HIRED' or employment_action = 'FIRED') 
);

CREATE OR REPLACE PROCEDURE create_log(
    first_name employment_logs.first_name%type, 
    last_name employment_logs.last_name%type, 
    employment_action employment_logs.employment_action%type,
    employment_status_updtd_tmstmp employment_logs.employment_status_updtd_tmstmp%type) 
IS 
BEGIN 
    INSERT INTO employment_logs(first_name, last_name, employment_action, employment_status_updtd_tmstmp)
    VALUES(first_name, last_name, employment_action, employment_status_updtd_tmstmp);
END;